Added netcat check

diff --git a/broadcaster-flash b/broadcaster-flash
--- a/broadcaster-flash
+++ b/broadcaster-flash
@@ -17,6 +17,20 @@ keyfile_check(){
 		echo "SSH Keyfile Not found!"
 	fi
 }
+netcat(){
+	nc $IP_address 22 < /dev/null &> /dev/null
+	if [[ $? -ne 0 ]]
+	then
+		echo "WARNING: Broadcaster not reachable via TCP 22!"
+	fi
+}
+netcat_diffPort(){
+	nc $IP_address $newPort < /dev/null &> /dev/null
+	if [[ $? -ne 0 ]]
+	then
+		echo "WARNING: Broadcaster not reachable via TCP $newPort !"
+	fi
+}
 copy_firmware(){
 	scp -i ~/.ssh/ls-remote.pem -o ConnectTimeout=20 /tmp/.firmware_upgrade root@$IP_address:/tmp && echo "sh /tmp/.firmware_upgrade" > /tmp/do_upgrade.txt && scp -i ~/.ssh/ls-remote.pem /tmp/do_upgrade.txt root@$IP_address:/tmp
 
@@ -44,9 +58,10 @@ then
 	then
 		echo "Attempting to connect via TCP 22..."
 		keyfile_check
-		copy_firmware || { echo "Connection failed. You may need to attempt via another port." \
+		netcat
+		copy_firmware || { echo "Connection failed. You may need to attempt via another port." ; \
 		echo "Enter Port :" && read newPort ; if [[ $newPort -gt 0 ]] ; then \
-		echo "Attempting through port $newPort" ; copy_firmware_diffPort && ssh_to_unit_diffPort ; else exit 0 ; fi; } || { exit 1; }
+		echo "Attempting through port $newPort" ; netcat_diffPort && copy_firmware_diffPort && ssh_to_unit_diffPort ; else exit 0 ; fi; } || { exit 1; }
 		ssh_to_unit
 		exit 0
 	else
@@ -55,8 +70,10 @@ then
 else
 	echo "Attempting to connect via TCP 22..."
 	keyfile_check
-	copy_firmware || { echo "Connection failed. You may need to attempt via another port." \ 
+	netcat
+	copy_firmware || { echo "Connection failed. You may need to attempt via another port." ;\
 		echo "Enter Port :" && read newPort ; if [[ $newPort -gt 0 ]] ; then \
-		echo "Attempting through port $newPort" ; copy_firmware_diffPort && ssh_to_unit_diffPort ; else exit 0 ; fi; } || { exit 1; }
+		echo "Attempting through port $newPort" ; netcat_diffPort && copy_firmware_diffPort && ssh_to_unit_diffPort ; else exit 0 ; fi; } || { exit 1; }
 	ssh_to_unit
 fi
+
